### ISSUE TITLE
PROP #1: Allocate 150,000 LPFi for zSOL-LPFi bonding on Penguin Finance

### ISSUE THREAD

**Issue by aperire** [LP-Finance-Inc/governance#1]
# PROP #1: Allocate 150,000 LPFi for zSOL-LPFi bonding on Penguin Finance

Date: Jan.26th 2023
Author: Joohwan Lee
Status: Executed

## Summary
I propose to allocate 150,000 LPFi from ["Liquidity" allocations](https://solscan.io/account/CeqR5ySV8sdUzhSdSKy2HLPLPeiKQeLcd4s7j8CkPteE) to create a bonding pool for zSOL-LPFi on Penguin Finance. Users would be able to provide zSOL-LPFi liquidity and transfer the LP token to LP Finance DAO to enhance protocol-owned-liquidity. Additionally, as the pair both involves zSOL and LPFi, it would bring positive impact to the protocol. 

## Motivation
Currently LPFi token lacks liquidity, which causes big slippage when swapping even small amounts. This proposal would be able to enhance LPFi liquidity immensely without spending funds from the team. However, by this action, 150,000 LPFi (3.4% of total supply) would be emitted with only 7 days vesting period. I believe this might be a negative impact short-term but would allow LPFi's price discovery to happen earlier with enhanced liquidity and more supply.

## Actions
1. Allocate 150,000 LPFi to Penguin Finance bonding pool
2. Lock zSOL-LPFi LP tokens in the following address. (HxPESVs8mM9SAMYtG8VDdphpx3okHjScmLqHUWyFJGPD)

**Comment by bene-coder** [comment]
Good idea. This will be a great move for the project

**Comment by AingCreation** [comment]
Cool sir

**Comment by yosrioh1** [comment]
Good idea

**Comment by aperire** [comment]
Taking this to on-chain voting

**Comment by aperire** [comment]
Proposal has passed.
<img width="1162" alt="Screenshot 2023-02-15 at 3 22 35 PM" src="https://user-images.githubusercontent.com/27561419/219145390-85e7599f-c959-43f2-9ea3-253c63a105a7.png">
